--- #------基础配置------
spring:
  application:
    name: paper-foreground
server:
  port: 8081
# springdoc-openapi项目配置，访问地址：http://127.0.0.1:8081/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '前台'
      paths-to-match: '/**'
      packages-to-scan: com.iyaovo.paper.foreground.controller


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: paper-cutting-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

--- #-------日志------
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    #  basic:
    #    enable: true
    # Basic账号
    #    username: root
    # Basic密码
#    password: 123456


--- #------mybatisplus------
mybatis-plus:
  global-config:
    db-config:
      # 主键类型：自增
      id-type: ASSIGN_ID
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # mapper xml文件路径
  mapper-locations: classpath:mapper/*.xml


--- #------数据库连接------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper-cutting?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 153426
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
#  redis:
#    host: localhost # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    timeout: 300ms # 连接超时时间（毫秒）

